CREATE TABLE IF NOT EXISTS admins (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  admin_id BIGINT UNSIGNED NOT NULL,
  token_hash BINARY(32) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE,
  INDEX idx_sessions_expiry (expires_at)
);
CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(12) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  title VARCHAR(160) NOT NULL,
  status ENUM('WAITING','ACTIVE','PAUSED','ENDED') NOT NULL DEFAULT 'WAITING',
  locked BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMP NULL,
  ended_at TIMESTAMP NULL,
  FOREIGN KEY (created_by) REFERENCES admins(id)
);
CREATE TABLE IF NOT EXISTS room_settings (
  room_id BIGINT UNSIGNED PRIMARY KEY,
  enabled_reactions JSON NOT NULL,
  reaction_rate_limit INT NOT NULL DEFAULT 5,
  default_display_mode VARCHAR(24) NOT NULL DEFAULT 'REACTIONS',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS display_tokens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  room_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  token_hash BINARY(32) NOT NULL UNIQUE,
  revoked_at TIMESTAMP NULL,
  last_seen_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  INDEX idx_display_room (room_id)
);
CREATE TABLE IF NOT EXISTS reaction_stats (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  room_id BIGINT UNSIGNED NOT NULL,
  bucket_at DATETIME NOT NULL,
  emoji VARCHAR(32) NOT NULL,
  count BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  UNIQUE KEY uq_room_bucket_emoji (room_id, bucket_at, emoji),
  INDEX idx_stats_room_time (room_id, bucket_at)
);
CREATE TABLE IF NOT EXISTS room_metrics (
  room_id BIGINT UNSIGNED PRIMARY KEY,
  total_reactions BIGINT UNSIGNED NOT NULL DEFAULT 0,
  peak_reactions_per_second BIGINT UNSIGNED NOT NULL DEFAULT 0,
  peak_concurrent_users INT UNSIGNED NOT NULL DEFAULT 0,
  unique_clients INT UNSIGNED NOT NULL DEFAULT 0,
  rate_limited_reactions BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS system_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  room_id BIGINT UNSIGNED NULL,
  level VARCHAR(16) NOT NULL DEFAULT 'info',
  event_type VARCHAR(64) NOT NULL,
  message VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL,
  INDEX idx_events_created (created_at)
);
